//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HitechTMS.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HitechTMS.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to add new record ? Because edited data will be loss on adding new record!.
        /// </summary>
        internal static string ADD_NEW {
            get {
                return ResourceManager.GetString("ADD_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert!.
        /// </summary>
        internal static string ALERT {
            get {
                return ResourceManager.GetString("ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross weight can not be blank!.
        /// </summary>
        internal static string CAN_NOT_BLANK_GROSS_WEIGHT {
            get {
                return ResourceManager.GetString("CAN_NOT_BLANK_GROSS_WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product code can&apos;t be blank.
        /// </summary>
        internal static string CAN_NOT_BLANK_PRD_CD {
            get {
                return ResourceManager.GetString("CAN_NOT_BLANK_PRD_CD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name can&apos;t be blank.
        /// </summary>
        internal static string CAN_NOT_BLANK_PRD_NM {
            get {
                return ResourceManager.GetString("CAN_NOT_BLANK_PRD_NM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tare weight can not be blank!.
        /// </summary>
        internal static string CAN_NOT_BLANK_TARE_WEIGHT {
            get {
                return ResourceManager.GetString("CAN_NOT_BLANK_TARE_WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck can not be blank!.
        /// </summary>
        internal static string CAN_NOT_BLANK_TRUCK {
            get {
                return ResourceManager.GetString("CAN_NOT_BLANK_TRUCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not save data please check your port settings!.
        /// </summary>
        internal static string CANNOT_SAVE_DATA_CHK_PORT_ST {
            get {
                return ResourceManager.GetString("CANNOT_SAVE_DATA_CHK_PORT_ST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check you Serial port settings!.
        /// </summary>
        internal static string CHCK_SERL_PRT_SET {
            get {
                return ResourceManager.GetString("CHCK_SERL_PRT_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close application ?.
        /// </summary>
        internal static string CLOSE_APPLICATION {
            get {
                return ResourceManager.GetString("CLOSE_APPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string CONFIRMATION {
            get {
                return ResourceManager.GetString("CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to permanently delete all the item ?.
        /// </summary>
        internal static string CONFIRMATION_DELETE {
            get {
                return ResourceManager.GetString("CONFIRMATION_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Deleted successfully!.
        /// </summary>
        internal static string DATA_DELETED {
            get {
                return ResourceManager.GetString("DATA_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data saved successfully!.
        /// </summary>
        internal static string DATA_SAVE {
            get {
                return ResourceManager.GetString("DATA_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kindly login again to see saved changes!.
        /// </summary>
        internal static string DATA_SAVE_RESTART_FOR_IMPACT {
            get {
                return ResourceManager.GetString("DATA_SAVE_RESTART_FOR_IMPACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data update successfully!.
        /// </summary>
        internal static string DATA_UPDATE {
            get {
                return ResourceManager.GetString("DATA_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date In.
        /// </summary>
        internal static string DATEIN {
            get {
                return ResourceManager.GetString("DATEIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Out.
        /// </summary>
        internal static string DATEOUT {
            get {
                return ResourceManager.GetString("DATEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete?.
        /// </summary>
        internal static string DELTE_POPUP {
            get {
                return ResourceManager.GetString("DELTE_POPUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission denied!.
        /// </summary>
        internal static string DENIED {
            get {
                return ResourceManager.GetString("DENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate data!.
        /// </summary>
        internal static string DUPLICATE_DATA {
            get {
                return ResourceManager.GetString("DUPLICATE_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sent successfully!.
        /// </summary>
        internal static string EMAIL_SENT {
            get {
                return ResourceManager.GetString("EMAIL_SENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password:.
        /// </summary>
        internal static string ENTER_PASS {
            get {
                return ResourceManager.GetString("ENTER_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in email sending. Please check email configuration settings!.
        /// </summary>
        internal static string ERR_EMAIL_CHK_CONFIG {
            get {
                return ResourceManager.GetString("ERR_EMAIL_CHK_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your delete request.
        /// </summary>
        internal static string ERROR_DELETE {
            get {
                return ResourceManager.GetString("ERROR_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in settings!.
        /// </summary>
        internal static string ERROR_SETTINGS {
            get {
                return ResourceManager.GetString("ERROR_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date from can&apos;t be greater than Date to.
        /// </summary>
        internal static string GREATER_DATE_ERR {
            get {
                return ResourceManager.GetString("GREATER_DATE_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross Weight.
        /// </summary>
        internal static string GROSS_WEIGHT {
            get {
                return ResourceManager.GetString("GROSS_WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross weight can not be less than Tare weight!.
        /// </summary>
        internal static string GROSS_WEIGHT_CAN_NOT_BE_LESS_THAN_TARE_WEIGHT {
            get {
                return ResourceManager.GetString("GROSS_WEIGHT_CAN_NOT_BE_LESS_THAN_TARE_WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information!.
        /// </summary>
        internal static string INFORMATION {
            get {
                return ResourceManager.GetString("INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight can not be more than max weight {0} !.
        /// </summary>
        internal static string MAX_WEIGHT {
            get {
                return ResourceManager.GetString("MAX_WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Weight is not set in General Settings!.
        /// </summary>
        internal static string MAX_WT_NOT_SET {
            get {
                return ResourceManager.GetString("MAX_WT_NOT_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        internal static string MISCELLANEOUS {
            get {
                return ResourceManager.GetString("MISCELLANEOUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi Weighing.
        /// </summary>
        internal static string MULTI_WEIGHING {
            get {
                return ResourceManager.GetString("MULTI_WEIGHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Weight.
        /// </summary>
        internal static string NET_WEIGHT {
            get {
                return ResourceManager.GetString("NET_WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data!.
        /// </summary>
        internal static string NO_DATA {
            get {
                return ResourceManager.GetString("NO_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Complete Weight.
        /// </summary>
        internal static string NORMAL_CHART_COMPLETE {
            get {
                return ResourceManager.GetString("NORMAL_CHART_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Pending Weight.
        /// </summary>
        internal static string NORMAL_CHART_PENDING {
            get {
                return ResourceManager.GetString("NORMAL_CHART_PENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Weighing.
        /// </summary>
        internal static string NORMAL_WEIGHING {
            get {
                return ResourceManager.GetString("NORMAL_WEIGHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port is not openned!.
        /// </summary>
        internal static string PORT_NOT_OPEN {
            get {
                return ResourceManager.GetString("PORT_NOT_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product code.
        /// </summary>
        internal static string PRODUCT_CODE {
            get {
                return ResourceManager.GetString("PRODUCT_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name.
        /// </summary>
        internal static string PRODUCT_NAME {
            get {
                return ResourceManager.GetString("PRODUCT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Weighing.
        /// </summary>
        internal static string PUBLIC_WEIGHING {
            get {
                return ResourceManager.GetString("PUBLIC_WEIGHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records not found!.
        /// </summary>
        internal static string RECORDS_NOT_FOUND {
            get {
                return ResourceManager.GetString("RECORDS_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross weight and Tare weight can not be same!.
        /// </summary>
        internal static string SAME_GROSS_AND_TARE_WEIGHT {
            get {
                return ResourceManager.GetString("SAME_GROSS_AND_TARE_WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least one record to print!.
        /// </summary>
        internal static string SELECT_PRINT {
            get {
                return ResourceManager.GetString("SELECT_PRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select records rows to delete!.
        /// </summary>
        internal static string SELECT_ROW_TO_DELETE {
            get {
                return ResourceManager.GetString("SELECT_ROW_TO_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System error!.
        /// </summary>
        internal static string SYS_ERR {
            get {
                return ResourceManager.GetString("SYS_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tare Weight.
        /// </summary>
        internal static string TARE_WEIGHT {
            get {
                return ResourceManager.GetString("TARE_WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tare weight can not be greater than Gross weight!.
        /// </summary>
        internal static string TARE_WEIGHT_CAN_NOT_BE_GREATER_THAN_GROSS_WEIGHT {
            get {
                return ResourceManager.GetString("TARE_WEIGHT_CAN_NOT_BE_GREATER_THAN_GROSS_WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time In.
        /// </summary>
        internal static string TIMEIN {
            get {
                return ResourceManager.GetString("TIMEIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Out.
        /// </summary>
        internal static string TIMEOUT {
            get {
                return ResourceManager.GetString("TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck.
        /// </summary>
        internal static string TRUCK {
            get {
                return ResourceManager.GetString("TRUCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name and Password doesn&apos;t match!.
        /// </summary>
        internal static string USER_NAME_PASSWORD_MISTMATCH {
            get {
                return ResourceManager.GetString("USER_NAME_PASSWORD_MISTMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to print the Ticket.
        /// </summary>
        internal static string WANT_PRINT_TICKET {
            get {
                return ResourceManager.GetString("WANT_PRINT_TICKET", resourceCulture);
            }
        }
    }
}
