//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Captions
    {
        public int Id { get; set; }
        public string DefaultCaption { get; set; }
        public string ModifiedCaptioin { get; set; }
        public int FormType { get; set; }
        public bool IsCaptionModified { get; set; }
        public System.Guid Identity { get; set; }
    }
}
