//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class mstHyoerTerminalData
    {
        public System.Guid Id { get; set; }
        public int BaudRate { get; set; }
        public int DataBits { get; set; }
        public int ReadTimeout { get; set; }
        public int WriteTimeout { get; set; }
        public string PortName { get; set; }
        public string Handshake { get; set; }
        public string Name { get; set; }
        public string DataReceived { get; set; }
        public string sParity { get; set; }
        public int iStopBits { get; set; }
    }
}
