//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class rptNormalTicket
    {
        public string ID { get; set; }
        public byte Mode { get; set; }
        public string Truck { get; set; }
        public string ProductCode { get; set; }
        public string Name { get; set; }
        public string SupplierCode { get; set; }
        public string SupplierName { get; set; }
        public string TransporterCode { get; set; }
        public string TarnsPorterName { get; set; }
        public string ChallanNumber { get; set; }
        public string Miscellaneous { get; set; }
        public string DeliveryNoteN { get; set; }
        public string ChallanWeight { get; set; }
        public string ChallanDate { get; set; }
        public string DateIn { get; set; }
        public string TimeIn { get; set; }
        public string DateOut { get; set; }
        public string TimeOut { get; set; }
        public string TareWeight { get; set; }
        public string NetWeight { get; set; }
        public string GrossWeight { get; set; }
        public byte ProdInOut { get; set; }
    }
}
