//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class transMultiWeight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public transMultiWeight()
        {
            this.MultiPrdWeight = new HashSet<MultiPrdWeight>();
        }
    
        public System.Guid ID { get; set; }
        public byte Mode { get; set; }
        public string Truck { get; set; }
        public Nullable<System.Guid> SupplierCode { get; set; }
        public Nullable<System.Guid> TransporterCode { get; set; }
        public string ChallanNumber { get; set; }
        public Nullable<System.DateTime> ChallanDate { get; set; }
        public Nullable<decimal> ChallanWeight { get; set; }
        public Nullable<byte> ChallanWeightUnit { get; set; }
        public string Miscellaneous { get; set; }
        public string DeliveryNoteN { get; set; }
        public Nullable<System.DateTime> DateIn { get; set; }
        public Nullable<System.DateTime> DateOut { get; set; }
        public Nullable<System.TimeSpan> TimeIn { get; set; }
        public Nullable<System.TimeSpan> TimeOut { get; set; }
        public Nullable<decimal> TareWeight { get; set; }
        public Nullable<decimal> GrossWeight { get; set; }
        public Nullable<decimal> NetWeight { get; set; }
        public byte ProdInOut { get; set; }
        public byte IsPending { get; set; }
        public System.DateTime AddedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MultiPrdWeight> MultiPrdWeight { get; set; }
    }
}
