//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_mstGeneralSettings
    {
        public System.Guid Id { get; set; }
        public int TransactionNo { get; set; }
        public string Mode { get; set; }
        public decimal MiniNetWeight { get; set; }
        public string StoreTare { get; set; }
        public string FirstWeightTkt { get; set; }
        public string TicketFormat { get; set; }
        public string ReportFormat { get; set; }
        public string TktRepPrintingMode { get; set; }
        public int HeaderBlankLine { get; set; }
        public int FooterBlankLine { get; set; }
        public System.DateTime AddedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    }
}
